wheel_radius: 0.341
wheel_width: 0.225
wheel_base: 2.950
wheel_tread: 1.55
vehicle_mass: 5000.0
vehicle_length: 4.82
vehicle_width: 1.81
vehicle_height: 1.5
minimum_turning_radius: 2.950
maximum_steering_angle: 97.3 #deg