mqtt:
  VEHICLEID: 1
  ADDRESS: localhost
  PORT: 1883
  QOS: 0
  TIMEOUT: 3000
  ACCEL_MAX_VAL: 100
  BRAKE_MAX_VAL: 10000
  STEER_MAX_VAL: 0.6
  LINEAR_X_MAX_VAL: 4.166
  CANINFO_DOWNSAMPLE: 0.1
  GEAR_D: 16
  GEAR_N: 32
  GEAR_R: 64
  GEAR_P: 128
